# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=34)),
            ],
        ),
    ]
