# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AciveDraftGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.IntegerField()),
                ('groupName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveDraftHeader',
            fields=[
                ('headerID', models.AutoField(primary_key=True, serialize=False)),
                ('headerName', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('fachrichtung', models.CharField(max_length=30)),
                ('stufe', models.IntegerField()),
                ('fach', models.CharField(max_length=30)),
                ('erstellungsdatum', models.DateField()),
                ('beschreibung', models.CharField(max_length=500)),
                ('startdatum', models.DateField()),
                ('enddatum', models.DateField()),
                ('teilnehmer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveDraftQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.IntegerField()),
                ('questionText', models.CharField(max_length=50)),
                ('answerType', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('option', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DraftGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.IntegerField()),
                ('text', models.CharField(default=b'', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DraftHeader',
            fields=[
                ('headerID', models.AutoField(primary_key=True, serialize=False)),
                ('headerName', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('fachrichtung', models.CharField(max_length=30)),
                ('stufe', models.IntegerField()),
                ('fach', models.CharField(max_length=30)),
                ('erstellungsdatum', models.DateField()),
                ('beschreibung', models.CharField(max_length=500)),
                ('sichtbarkeit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DraftQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.IntegerField()),
                ('questionText', models.CharField(max_length=50)),
                ('answerType', models.CharField(max_length=4)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.DraftGroups')),
                ('headerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.DraftHeader')),
            ],
        ),
        migrations.AddField(
            model_name='draftgroups',
            name='headerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.DraftHeader'),
        ),
        migrations.AddField(
            model_name='activedraftquestion',
            name='groupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.DraftGroups'),
        ),
        migrations.AddField(
            model_name='activedraftquestion',
            name='headerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.DraftHeader'),
        ),
        migrations.AddField(
            model_name='acivedraftgroups',
            name='headerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eva.DraftHeader'),
        ),
    ]
