# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0002_auto_20160607_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftheader',
            name='autor',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='draftheader',
            name='beschreibung',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='draftheader',
            name='erstellungsdatum',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='draftheader',
            name='fach',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='draftheader',
            name='fachrichtung',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='draftheader',
            name='headerName',
            field=models.CharField(default=b'', max_length=30),
        ),
        migrations.AlterField(
            model_name='draftheader',
            name='sichtbarkeit',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='draftheader',
            name='stufe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='draftquestion',
            name='answerType',
            field=models.CharField(default=b'', max_length=4),
        ),
        migrations.AlterField(
            model_name='draftquestion',
            name='questionText',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
